### ISSUE TITLE
关于 packagejson 中 设置 '"type": "module"' 时 webpack打包报错问题

### ISSUE THREAD

**Issue by TunnelHunter** [yusangeng/runtime-import#10]
![image](https://user-images.githubusercontent.com/37205419/155927973-9289eefe-2723-46f4-a1c8-d85e6b1b9c20.png)
esm规范为  npm packagejson 在配置type：module 时 打包文件内的文件引用 应该都需要带文件后缀才行。目前runtime-import包的ts编译产出文件内 文件引用都没后缀 导致webpack 打包报错。
目前解决方案如下：
https://webpack.js.org/api/module-methods/
Rule.resolve.fullySpecified = false 

但终极方案 还是开发者 把 package.json 中 type：module 去掉 或者 把编译后的文件引用全部加上后缀

**Comment by yusangeng** [comment]
感谢，因为自用的构建工具默认有这个配置，测试也没覆盖这种情况，导致这个问题出现。

我研究一下如何改比较周全。

**Comment by Ezreal09** [comment]
> 感谢，因为自用的构建工具默认有这个配置，测试也没覆盖这种情况，导致这个问题出现。
> 
> 我研究一下如何改比较周全。

这个有更新吗，我试了一下还是不行

**Comment by ZephyrTan** [comment]
这个问题好像现在还是没有解决，我也遇到了

**Comment by yusangeng** [comment]
已解决，版本3.0.0-beta.0
