### ISSUE TITLE
CORS error occur when loading a cross origin script

### ISSUE THREAD

**Issue by weibinzhu** [yusangeng/runtime-import#2]
when I trying to load a cross origin script, a CORS error occur.
<img width="885" alt="Screen Shot 2021-02-04 at 14 48 46" src="https://user-images.githubusercontent.com/15839182/106855572-18448b80-66f8-11eb-9d3a-d159721c482f.png">
seems like this line is the reason:
```
el.crossOrigin = 'anonymous'; // 避免window.onerror拿不到脚本的报错
```
> The crossorigin attribute should only be used if we care about getting error information for the script being loaded. Since accessing this information requires a CORS check, the Access-Control-Allow-Origin header must be present on the resource for it to be loaded.

reference: [With <script crossorigin='anonymous'>, why is a script “blocked by CORS policy”?](https://stackoverflow.com/questions/41069330/with-script-crossorigin-anonymous-why-is-a-script-blocked-by-cors-policy#:~:text=crossorigin%20attribute%20has%20only%20two,will%20be%20translated%20to%20anonymous%20.&text=This%20tag%20will%20run%20script,skip%20Origin%20HTTP%20header%20entirely).

**Comment by yusangeng** [comment]
importModule时通过crossOrigin配置可以规避这个问题。
