### ISSUE TITLE
Can NOT find item

### ISSUE THREAD

**Issue by shenjo** [yusangeng/runtime-import#3]
when `importScript('/main.js')`, actually the browser will load the script in current server envrienment. e.g. `http://localhost:3000/main.js` . thus pendingItemMap cannot match the script. throw this error.
![image](https://user-images.githubusercontent.com/13912646/144370377-9a0cab9c-49d6-4205-b901-1a509536a9b8.png)

**Comment by shenjo** [comment]
replace `window.location.protocol` with `window.location.origin`?

**Comment by yusangeng** [comment]
> when `importScript('/main.js')`, actually the browser will load the script in current server envrienment. e.g. `http://localhost:3000/main.js` . thus pendingItemMap cannot match the script. throw this error. ![image](https://user-images.githubusercontent.com/13912646/144370377-9a0cab9c-49d6-4205-b901-1a509536a9b8.png)

Thank you. It seems like problem about relative URL，I'm going to test it.

**Comment by yusangeng** [comment]
> replace `window.location.protocol` with `window.location.origin`?

Iguess `protocol` and `origin` are both necessary.

**Comment by yusangeng** [comment]
Bug fixed, version: 2.1.0
