### ISSUE TITLE
如果远程的js有externals，则会报错。

### ISSUE THREAD

**Issue by hengwangm** [yusangeng/runtime-import#5]
![image](https://user-images.githubusercontent.com/22046412/150955011-2c0a0580-a897-41b4-82f4-337a40ad4eb7.png)
如图所示，走入amd之后，会从factory去拿这些依赖

**Comment by yusangeng** [comment]
@hengwangm 
按照设计目标，对于被runtime-import的脚本，define应该是替换过的，external逻辑应该为找全局变量。
我验证一下你说的情况。

能否告知一下你构建umd文件使用的工具链和版本？因为不同工具构建出来的umd可能不太一致。

**Comment by hengwangm** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/22046412/154398030-832696ad-efdd-4ec7-ac39-b849eb9519e4.png">
直接使用的'@babel/plugin-transform-modules-umd'进行转换
