### ISSUE TITLE
Access to script at 'xxx' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by 953133667** [yusangeng/runtime-import#9]
我在使用这个包的时候，报了一个错，这个问题主要是因为跨域拦截 导致的

**Comment by yusangeng** [comment]
请问是否是在https的网页里面访问了http的脚本？目前采用的加载方式是创建script标签，不会因为域名不一样被跨域规则拦住。

**Comment by 953133667** [comment]
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/9947354/156719060-212bf6c3-7a0a-4548-b90f-079f68ed3894.png">

<script src="./plugins/toolbar.min.js" crossorigin="anonymous"></script>

crossorigin  这个属性，应该默认不传的时候，不要这个属性的 ，不然如果我尝试直接访问一些网络资源， 例如一些 JS CDN 服务，或者本地资源，都会被 跨域拦截掉。但是目前默认的处理方案是 设置为 crossorigin="anonymous"，且无法删除该属性，这不太合理

**Comment by yusangeng** [comment]
> <img alt="image" width="1696" src="https://user-images.githubusercontent.com/9947354/156719060-212bf6c3-7a0a-4548-b90f-079f68ed3894.png">
> 
> <script src="./plugins/toolbar.min.js" crossorigin="anonymous"></script>
> crossorigin 这个属性，应该默认不传的时候，不要这个属性的 ，不然如果我尝试直接访问一些网络资源， 例如一些 JS CDN 服务，或者本地资源，都会被 跨域拦截掉。但是目前默认的处理方案是 设置为 crossorigin="anonymous"，且无法删除该属性，这不太合理

如果要禁止crossOrigin，可以在importModule函数的options参数中将crossOrigin选项设为""（空字符串）。

之所以设置默认的crossorigin属性，是因为第三方脚本如果没有这个属性，埋码监控的异常报警就抓不到调用栈了，对于产品级系统我们认为这是不可接受的。

另外，目前的CDN服务（比如阿里云、腾讯云）大都支持跨域策略设置，是可以允许crossorigin="anonymous"的。

@[953133667](https://github.com/953133667)

**Comment by yusangeng** [comment]
README中添加了文档说明以防用户由于注意不到crossOrigin选项导致使用困难。

考虑到上层应用的稳定性，暂时不改变crossorigin的设置策略。

**Comment by 953133667** [comment]
crossorigin  属性默认去掉，兼容性应该会更好一些
